### ISSUE TITLE
AES解密异常：Given final block not properly padded

### ISSUE THREAD

**Issue by ybp825** [Licoy/encrypt-body-spring-boot-starter#1]
AES解密异常javax.crypto.BadPaddingException: Given final block not properly padded，类：cn.licoy.encryptbody.util.AESEncryptUtil

**Comment by Licoy** [comment]
@ybp825 麻烦请贴出相关使用代码用例，以帮助更好的排错~

**Comment by ybp825** [comment]
mac os系统

`String encrypt = AESEncryptUtil.encrypt("12312", "12345678");
encrypt = AESEncryptUtil.decrypt(encrypt, "12345678");
System.out.println(encrypt);`
控制台信息：
javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:975)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:833)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at cn.licoy.encryptbody.util.AESEncryptUtil.aes(AESEncryptUtil.java:55)
	at cn.licoy.encryptbody.util.AESEncryptUtil.decrypt(AESEncryptUtil.java:32)

**Comment by Licoy** [comment]
我这边测试没有问题的，请问您的JDK版本是多少？

![QQ截图20181009165314.png](https://i.loli.net/2018/10/09/5bbc6c85939f2.png)

**Comment by ybp825** [comment]
> 我这边测试没有问题的，请问您的JDK版本是多少？
> 
> ![QQ截图20181009165314.png](https://camo.githubusercontent.com/8a95af22b74c8741925ae2b40eb1bad13c8d9867/68747470733a2f2f692e6c6f6c692e6e65742f323031382f31302f30392f356262633663383539333966322e706e67)
版本信息：
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Licoy** [comment]
@ybp825 版本是1.8+没问题 我这边BUG重现不好复原，我调试一下吧
