### ISSUE TITLE
   Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

### ISSUE THREAD

**Issue by LUCKYZHOUSTAR** [Licoy/encrypt-body-spring-boot-starter#10]
hi，when user the des encrypt, meet the error.

Firstly,when I just test the dncrpty method using main method, that is ok
  @Test
    public void test1() {

        for (int i = 0; i < 100; i++) {
            System.out.println(DESCryptography.dncrypt("F62AC256E0778C87"));

        }

    }

but , unhappily ,when I start my spring boot web ,just write this:
 public static void main(String... args) {

        ApplicationContext context = SpringApplication.run(WalletDriver.class, args);

        for (int i = 0; i < 100; i++) {
            System.out.println(DESCryptography.dncrypt("F62AC256E0778C87"));
        }
    }

 I meet the error：
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
	at java.base/com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)

Until now,i can not found how to resolve the problem

**Comment by bangaromaric** [comment]
Hello @LUCKYZHOUSTAR, I have also this issue, 
Have you fix it ?
thanks

**Comment by Licoy** [comment]
There are some problems with the current version, so it is not recommended

**Comment by Licoy** [comment]
本项目已停止维护

替代品搜索：https://github.com/search?q=encrypt&type=Repositorieshttps://github.com/search?l=Java&q=encrypt&type=Repositories

**Comment by Licoy** [comment]
@LUCKYZHOUSTAR @bangaromaric this issue has been updated in the latest version

**Comment by bangaromaric** [comment]
thanks, I'll give you a feedback
Cordialement.
*------------------------------------------------------ *
*BANGA Romaric*
Google Certified Associate Android Developer <https://sgq.io/BMNDL2I>
Spring Boot developper
Lead Organizer of Google Developer Groups Libreville
<https://bit.ly/gdglbvweb>



***@***.***, Twitter <https://twitter.com/bangaromaric>, Facebook
<https://www.facebook.com/bangaromaric>

Tel: +241066127676
