### ISSUE TITLE
加密之后解密含有中文的 都是问号，请问怎么处理？

### ISSUE THREAD

**Issue by Alwaysso** [Licoy/encrypt-body-spring-boot-starter#11]
加密之后解密含有中文的 都是问号，请问怎么处理

**Comment by Licoy** [comment]
部分加密方式中文是会存在不适配问题，目前暂未解决不推荐使用

**Comment by Licoy** [comment]
本项目已停止维护

替代品搜索：https://github.com/search?q=encrypt&type=Repositorieshttps://github.com/search?l=Java&q=encrypt&type=Repositories

**Comment by Licoy** [comment]
@Alwaysso this issue has been updated in the latest version
