### ISSUE TITLE
Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

### ISSUE THREAD

**Issue by YangSimon** [Licoy/encrypt-body-spring-boot-starter#4]
依然还是出现这个问题, SSM框架,tomcat是9.0.13, java version "1.8.0_181"
![1](https://user-images.githubusercontent.com/8643888/51302943-da239300-1a6e-11e9-9b40-7a85a915c2d9.png)
1.是SSM的一个项目,写的方法,
![2](https://user-images.githubusercontent.com/8643888/51302948-db54c000-1a6e-11e9-88d6-71f8ab90b13b.png)
2.ssm项目控制台打印的结果
![3](https://user-images.githubusercontent.com/8643888/51302951-dbed5680-1a6e-11e9-812b-5a8ccd49646a.png)
3.springboot项目,接受参数

**Comment by YangSimon** [comment]
![4](https://user-images.githubusercontent.com/8643888/51303029-13f49980-1a6f-11e9-9d5e-ade435d6af85.png)

**Comment by Licoy** [comment]
这种的要确认一下前端的加密与后端的加密的结果是否一致，有时候前后端相同算法的加密的结果可能存在差异
