### ISSUE TITLE
改进配合前端cryptojs进行整合

### ISSUE THREAD

**Issue by Licoy** [Licoy/encrypt-body-spring-boot-starter#7]
todo

**Comment by jwencode** [comment]
请问大概什么时候会上线前端加解密的案例？我在使用VUE项目中需要用到，想自己写，但是加密这块不太懂。`KeyGenerator generator = KeyGenerator.getInstance("AES");
            SecureRandom random = SecureRandom.getInstance("SHA1PRNG");
            random.setSeed(password.getBytes());
            generator.init(128, random);
            SecretKey secretKey = generator.generateKey();
            byte[] enCodeFormat = secretKey.getEncoded();
            SecretKeySpec key = new SecretKeySpec(enCodeFormat, "AES");
            Cipher cipher = Cipher.getInstance("AES");
            cipher.init(type, key);`  不知道怎么改为前端js代码。

**Comment by Licoy** [comment]
本项目已停止维护

替代品搜索：https://github.com/search?q=encrypt&type=Repositorieshttps://github.com/search?l=Java&q=encrypt&type=Repositories

**Comment by Licoy** [comment]
@jwencode 在最新发行版中已经支持
