### ISSUE TITLE
RSA

### ISSUE THREAD

**Issue by wuxinvip** [Licoy/encrypt-body-spring-boot-starter#8]
为啥现在还不支持RSA

**Comment by Licoy** [comment]
欢迎提交pr

**Comment by Licoy** [comment]
本项目已停止维护

替代品搜索：https://github.com/search?q=encrypt&type=Repositorieshttps://github.com/search?l=Java&q=encrypt&type=Repositories

**Comment by Licoy** [comment]
@wuxinvip this issue has been updated in the latest version
