### ISSUE TITLE
继承重新实现

### ISSUE THREAD

**Issue by wuxinvip** [Licoy/encrypt-body-spring-boot-starter#9]
博主、你写的这东西能不能给人继承下？

**Comment by wuxinvip** [comment]
@Order(1)
@ControllerAdvice
@Slf4j
public class EncryptResponseBodyHandler extends EncryptResponseBodyAdvice {

......................
}

**Comment by Licoy** [comment]
你可以试试

**Comment by Licoy** [comment]
本项目已停止维护

替代品搜索：https://github.com/search?q=encrypt&type=Repositorieshttps://github.com/search?l=Java&q=encrypt&type=Repositories
